Repository ultrabug/py3status, pull requests merged in 2018-10, with the labels that each got.

#1539 module_test: print modules in terminal
  doc/writing_modules.rst
  py3status/module_test.py
Labels: enhancement :heart_eyes:

#1408 Allow module to use the general "markup" config
  py3status/module.py
Labels: bug fix :bug:, enhancement :heart_eyes:

#1480 py3: add threshold string support
  py3status/py3.py
Labels: enhancement :heart_eyes:

#1549 adds ~/.config/i3 as a default config directory, closes #1548
  py3status/cli.py
Labels: bug fix :bug:

#1546 implement udev event monitoring
  doc/configuration.rst
  py3status/constants.py
  py3status/core.py
  py3status/module.py
  py3status/modules/xrandr.py
  py3status/udev_monitor.py
Labels: enhancement :heart_eyes:

#1553 parse_config: raise error on invalid modules
  py3status/parse_config.py
Labels: bug fix :bug:

#1556 py3: notify_user module name in the title
  py3status/py3.py
Labels: enhancement :heart_eyes:

#1558 allow test_modules to use udev_monitor
  py3status/module_test.py
Labels: bug fix :bug:, ready for merge :+1:
