Repository ultrabug/py3status, pull requests merged in 2018-12, with the labels that each got.

#1586 screenshots: fix parsing missing last screenshots
  py3status/screenshots.py
Labels: bug fix :bug:

#1570 vnstat: replace deprecated --exportdb with --oneline
  py3status/modules/vnstat.py
Labels: bug fix :bug:, ready for merge :+1:

#1596 vpn_status: handle multiple simultaneous vpn connections
  py3status/modules/vpn_status.py
Labels: enhancement :heart_eyes:

#1595 formatter: avoid duplicate soft blocks
  py3status/formatter.py
Labels: bug fix :bug:

#1589 py3-cmd: allow sending click events with modifiers
  py3status/command.py
Labels: enhancement :heart_eyes:

#1265 Async script (low-prio)
  py3status/modules/async_script.py
Labels: new module :sparkles:

#1275 Added emerge status module
  py3status/modules/emerge_status.py
Labels: new module :sparkles:

#1458 New module: MEGA sync
  py3status/modules/mega.py
Labels: new module :sparkles:

#1435 New module: speedtest
  py3status/modules/speedtest.py
Labels: new module :sparkles:

#1376 Usbguard module
  py3status/modules/usbguard.py
  tests/test_module_doc.py
Labels: new module :sparkles:

#1515 New module: Velib metropole
  py3status/modules/velib_metropole.py
Labels: new module :sparkles:

#1486 module: add background and border colors
  py3status/module.py
Labels: enhancement :heart_eyes:

#1608 modules: don't set module options on failed modules
  py3status/module.py
Labels: bug fix :bug:

#1471 do_not_disturb: new module from scratch
  py3status/modules/do_not_disturb.py
Labels: dangerous :bomb:
