Repository ultrabug/py3status, pull requests merged in 2018-09, with the labels that each got.

#1474 fix empty seeming composite block issue
  py3status/formatter.py
  tests/test_formatter.py
Labels: bug fix :bug:, ready for merge :+1:

#1463 gitlab: hide {name} placeholder when offline
  py3status/modules/gitlab.py
Labels: dangerous :bomb:

#1475 external_script: cast numeric output automatically
  py3status/modules/external_script.py
Labels: bug fix :bug:

#1473 sql: don't make placeholders case-sensitive
  py3status/modules/sql.py
Labels: bug fix :bug:

#1488 Urgent: fix BOM related documentation breakage
  py3status/py3.py
Labels: black star :star:, bug fix :bug:

#1491 py3status lexer updates for docs
  py3status/autodoc.py
Labels: enhancement :heart_eyes:

#1482 config parser: add explicit exceptions
  py3status/parse_config.py
Labels: bug fix :bug:

#1495 parse_config: fix issue caused by lack of testing
  py3status/parse_config.py
Labels: black star :star:, bug fix :bug:

#1489 config parser: cleaner functions
  doc/configuration.rst
  py3status/parse_config.py
Labels: enhancement :heart_eyes:

#1493 sysdata: add htop-like memory usage
  py3status/modules/sysdata.py
Labels: dangerous :bomb:

#1503 parse_config: decode bytes
  py3status/parse_config.py
Labels: bug fix :bug:

#1506 timewarrior: fix cosemitc issues with format_duration
  py3status/modules/timewarrior.py
Labels: ready for merge :+1:

#1485 module: default left align instead of center
  py3status/module.py
Labels: ready for merge :+1:

#1511 sysdata: fix swap indexerror exception
  py3status/modules/sysdata.py
Labels: bug fix :bug:

#1517 timewarrior: pass action/id index
  py3status/modules/timewarrior.py
Labels: bug fix :bug:
