Repository ultrabug/py3status, pull requests merged in 2018-08, with the labels that each got.

#1389 file_status: patch to fix plural wording
  py3status/modules/file_status.py
Labels: ★

#1417 add new module: loadavg
  py3status/modules/loadavg.py
Labels: new module

#1424 formatter: add {:ceil} to return x or x+1
  py3status/formatter.py
  tests/test_formatter.py
Labels: ★

#1420 formatter: don't strip whitespace
  py3status/formatter.py
Labels: ★

#1419 formatter: hide block on 'None' string too
  py3status/formatter.py
  tests/test_formatter.py
Labels: ★

#1426 formatter: show values instead of faking nonexistent keys
  py3status/formatter.py
Labels: ★

#1428 py3: threshold_get_colors to allow name with different values
  py3status/py3.py
Labels: ★

#1294 add new module: lm_sensors
  py3status/modules/lm_sensors.py
Labels: new module

#1413 setup: add fast-entry_points
  MANIFEST.in
  fastentrypoints.py
  setup.py
Labels: ★

#1134 add new module: nvidia_smi
  py3status/modules/nvidia_smi.py
Labels: new module

#1412 parse_config: fix lookuperror exception
  py3status/parse_config.py
Labels: ★

#1210 add new module: mail
  py3status/modules/mail.py
Labels: new module

#1221 formatter: return falsey properly
  py3status/formatter.py
  tests/test_formatter.py
Labels: ★

#1436 module: align modules with py3status instead of i3bar
  py3status/module.py
Labels: :star:, enhancement

#1447 add new module: wanda_the_fish
  py3status/modules/wanda_the_fish.py
Labels: :star:, new module

#1411 storage: use $XDG_CACHE_HOME or ~/.cache (+many more)
  doc/configuration.rst
  py3status/storage.py
Labels: black star :star:, dangerous :bomb:, enhancement :heart_eyes: :heart_eyes: :heart_eyes:

#1150 add new module: timewarrior
  py3status/modules/timewarrior.py
Labels: new module :sparkles:

#1455 allow us to get params from formats and also update them
  py3status/formatter.py
  tests/test_formatter.py
Labels: enhancement :heart_eyes:

#1466 clock: use format parsing to find placeholder
  py3status/modules/clock.py
Labels: enhancement :heart_eyes:

#1461 fedora-updates: fix issue caused by lack of testing
  py3status/modules/fedora_updates.py
Labels: bug fix :bug:

#1460 weather_owm: work without timezoneapi but also if you set city or location
  py3status/modules/weather_owm.py
Labels: enhancement :heart_eyes:

#1470 timew: fix future bug caused by copy and paste
  py3status/modules/timewarrior.py
Labels: bug fix :bug:
