Repository ultrabug/py3status, pull requests merged in 2019-03, with the labels that each got.

#1703 wifi: remove use_sudo in favor of auto
  py3status/modules/wifi.py
Labels: NAK 👎

#1732 weather_owm: flip coordinates to (lat, lon)
  py3status/modules/weather_owm.py
Labels: bug fix :bug:

#1718 add i3/sway directive
  README.rst
  doc/intro.rst
  py3status/argparsers.py
  py3status/core.py
  py3status/events.py
  py3status/module_test.py
  py3status/modules/google_calendar.py
  py3status/modules/scratchpad_counter.py
  py3status/modules/window_title.py
  py3status/modules/xrandr.py
  py3status/py3.py
Labels: black star :star:

#1751 battery_level: Fix case when an invalid battery is detected
  py3status/modules/battery_level.py
Labels: bug fix :bug:

#1748 add new module: scroll
  py3status/modules/scroll.py
Labels: new module :sparkles:

#1749 module: fix indexerror exception
  py3status/module.py
Labels: bug fix :bug:

#1753 Group stop cycling on urgent module closes #890
  py3status/module.py
  py3status/modules/group.py
Labels: enhancement :heart_eyes:

#1745 update i3wm.github.io py3status page with newer links and doc fix #1010
  doc/py3status.html
Labels: enhancement :heart_eyes:

#1747 parse_config: raise errors on sections in containers in the order directive
  py3status/events.py
  py3status/parse_config.py
Labels: bug fix :bug:

#1757 group: don't cycle on zero
  py3status/modules/group.py
Labels: bug fix :bug:

#1759 mpris: handle disconnected players gracefully on clicks
  py3status/modules/mpris.py
Labels: bug fix :bug:

#1758 I3pystatus: support universal/py3status module options
  py3status/modules/i3pystatus.py
Labels: bug fix :bug:
