Repository ultrabug/py3status, pull requests merged in 2019-01, with the labels that each got.

#1609 added cpufreq module
  py3status/modules/sysdata.py
Labels: enhancement :heart_eyes:

#1615 mpd_status module: max_width not working because of composite fix #1613
  py3status/modules/mpd_status.py
Labels: bug fix :bug:

#1618 notify users of obsolete module and their alternatives
  py3status/constants.py
  py3status/parse_config.py
Labels: black star :star:

#1624 do_not_disturb module: fix pause logic hiding startup notifications
  py3status/modules/do_not_disturb.py
Labels: bug fix :bug:

#1623 Update contribution guidelines
  doc/contributing.rst
Labels: ready for merge :+1:

#1633 velib_metropole: fix format thresholds
  py3status/modules/velib_metropole.py
Labels: bug fix :bug:

#1631 py3: get_color_names_list to return an empty list on false value
  py3status/py3.py
Labels: bug fix :bug:

#1634 py3: threshold_get_color to set color=None on exception
  py3status/py3.py
Labels: bug fix :bug:

#1643 fix black check mode which should fail the CI if reformatting is needed
  tests/test_method_mismatch.py
  tox.ini
Labels: bug fix :bug:

#1649 i3status: add -u, --i3status to specify i3status path
  py3status/cli.py
  py3status/core.py
  py3status/i3status.py
Labels: enhancement :heart_eyes:

#1648 mpris: fix clementine attributeerror exception
  py3status/modules/mpris.py
Labels: bug fix :bug:

#1654 dnd: simplify dunst logic
  py3status/modules/do_not_disturb.py
Labels: ready for merge :+1:

#1655 exchange_rate: change feed to exchangeratesapi.io
  py3status/modules/exchange_rate.py
Labels: bug fix :bug:

#1664 add new module: conky
  py3status/modules/conky.py
Labels: new module :sparkles:

#1662 i3status: use None or i3status
  py3status/cli.py
Labels: bug :disappointed:

#1627 module: add urgent background and borders
  doc/configuration.rst
  py3status/module.py
Labels: enhancement :heart_eyes:, ready for merge :+1:

#1667 cli, core: refactor cli stuff from core to cli
  py3status/cli.py
  py3status/core.py
Labels: black star :star:
