Repository ultrabug/py3status, pull requests merged in 2019-04, with the labels that each got.

#1762 i3pystatus: remove composites and keys to make dicts more comparable
  py3status/modules/i3pystatus.py
Labels: bug fix :bug:

#1770 pomodoro: use py3.play_sound helper
  py3status/modules/pomodoro.py
  py3status/py3.py
Labels: bug fix :bug:

#1773 py3: add multiple get_placeholders_list
  py3status/py3.py
Labels: enhancement :heart_eyes:

#1761 mpris: make new default changes
  py3status/modules/mpris.py
Labels: bug fix :bug:, dangerous :bomb:

#1741 khal module
  py3status/modules/khal_calendar.py
Labels: new module :sparkles:

#1784 module: fix pango markup for non-composite modules
  py3status/module.py
Labels: bug fix :bug:

#1785 group: calculate remaining times to cycle more accurately
  py3status/modules/group.py
Labels: NAK 👎, bug fix :bug:
