Repository ultrabug/py3status, pull requests merged in 2019-08, with the labels that each got.

#1823 Introduce entry point based discovery of packaged custom modules
  doc/writing_modules.rst
  py3status/core.py
  py3status/module.py
  tests/test_user_modules.py
Labels: enhancement :heart_eyes:

#1831 mpris module: fix KeyError exception
  py3status/modules/mpris.py
Labels: bug fix :bug:

#1832 Mpris module: Fix AttributeError: 'MockPy3statusWrapper' object has no attribute 'is_gevent'
  py3status/module_test.py
Labels: bug fix :bug:

#1766 wifi_nm: Display WiFi info using NetworkManager.
  py3status/modules/networkmanager.py
Labels: new module :sparkles:
