Repository ultrabug/py3status, pull requests merged in 2019-12, with the labels that each got.

#1861 [module] systemd suspend inhibitor
  py3status/modules/systemd_suspend_inhibitor.py
Labels: new module :sparkles:

#1870 brightness : use logind as a fallback
  py3status/modules/backlight.py
Labels: enhancement :heart_eyes:

#1869 xkb_input: new module from scratch to support sway too
  py3status/constants.py
  py3status/modules/xkb_input.py
  py3status/modules/xkb_layouts.py
Labels: new module :sparkles:

#1872 spaceapi: fix offline attributeerror exception
  py3status/modules/spaceapi.py
Labels: bug fix :bug:

#1876 getjson module: support basic auth via username/password fix #1875
  py3status/modules/getjson.py
Labels: enhancement :heart_eyes:
