Repository ultrabug/py3status, pull requests merged in 2020-09, with the labels that each got.

#1946 Support more battery in battery_level module
  py3status/modules/battery_level.py
Labels: enhancement :heart_eyes:

#1948 py3 - update for google_calendar.py
  py3status/modules/google_calendar.py
Labels: enhancement :heart_eyes:

#1947 Prometheus query module.
  py3status/modules/prometheus.py
Labels: new module :sparkles:

#1949 Skip batteries with missing info
  py3status/modules/battery_level.py
Labels: bug fix :bug:
